name: Java CI Ubuntu Latest

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-25.10

    steps:
      - name: Install GCC
        run: sudo apt-get update && sudo apt-get install -y gcc=15.2.0

      - name: Install CMake
        run: sudo apt-get update && sudo apt-get install -y cmake=3.31.6

      - name: Install SWIG
        run: sudo apt-get update && sudo apt-get install -y swig=4.3.0

      - name: Checkout HiGHS
        uses: actions/checkout@v4
        with:
          repository: ERGO-Code/HiGHS
          ref: v1.12.0
          path: HiGHS

      - name: Build HiGHS
        run: |
          cd HiGHS
          cmake -S . -B build
          cmake --build build --parallel
          ctest

      - name: Set HIGHS_HOME
        run: |
          echo "HIGHS_HOME=$(pwd)/HiGHS" >> $GITHUB_ENV

      - name: Verify HIGHS_HOME
        run: |
          echo "HIGHS_HOME is set to: $HIGHS_HOME"

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'

      - uses: actions/checkout@v4

      - name: Generate JNI classes
        run: |
          chmod +x ./generate_jni_classes
          ./generate_jni_classes
        env:
          HIGHS_HOME: ${{ env.HIGHS_HOME }}
          JAVA_HOME: ${{ env.JAVA_HOME }}

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run Tests
        run: mvn test