name: Ubuntu Latest

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        java: [ '23', '24', '25' ]
        compiler: [ 'gcc', 'clang' ]
        os: [ ubuntu-latest ]

    name: Build with JDK ${{ matrix.java }} and ${{ matrix.compiler }}

    steps:
      - name: Install GCC
        if: matrix.compiler == 'gcc'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc g++
          echo "CC=gcc" >> $GITHUB_ENV
          echo "CXX=g++" >> $GITHUB_ENV

      - name: Install Clang
        if: matrix.compiler == 'clang'
        run: |
          sudo apt-get update
          sudo apt-get install -y clang
          echo "CC=clang" >> $GITHUB_ENV
          echo "CXX=clang++" >> $GITHUB_ENV

      - name: Install CMake
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake

      - name: Install SWIG
        run: |
          sudo apt-get update
          sudo apt-get install -y swig

      - name: Checkout HiGHS
        uses: actions/checkout@v4
        with:
          repository: ERGO-Code/HiGHS
          ref: v1.12.0
          path: HiGHS

      - name: Build HiGHS
        run: |
          echo "HIGHS_HOME=$(pwd)/HiGHS" >> $GITHUB_ENV
          cd HiGHS
          cmake -S . -B build -DCMAKE_BUILD_TYPE=RELEASE -DHIGHSINT64=on
          cmake --build build --parallel --config RELEASE
          cd build
          ctest

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Checkout project
        uses: actions/checkout@v4
        with:
          path: Wrapper

      - name: Generate shared libraries
        run: |
          cd Wrapper
          $CC --version
          $CXX --version
          chmod +x ./generate_shared_libraries
          ./generate_shared_libraries

      - name: Run Tests
        run: |
          cd Wrapper
          mvn test